// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDklkKTVOHJocewibIz-DWNkU545R3YCos',
    appId: '1:823827220859:web:343ff111f44e77a8dad5de',
    messagingSenderId: '823827220859',
    projectId: 'tali-khata-da2cd',
    authDomain: 'tali-khata-da2cd.firebaseapp.com',
    storageBucket: 'tali-khata-da2cd.firebasestorage.app',
    measurementId: 'G-GSKPMC9H4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEbKQlJrJPjT_pbJdbxRGAiIy7AXtxyzs',
    appId: '1:823827220859:android:e55c145e6b678b59dad5de',
    messagingSenderId: '823827220859',
    projectId: 'tali-khata-da2cd',
    storageBucket: 'tali-khata-da2cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLocxpphOVTQOt9MTz5LYaQ4Qqyf8VLEI',
    appId: '1:823827220859:ios:18796251b64ee06bdad5de',
    messagingSenderId: '823827220859',
    projectId: 'tali-khata-da2cd',
    storageBucket: 'tali-khata-da2cd.firebasestorage.app',
    iosBundleId: 'com.example.taliKhata',
  );
}
